Repository kellnerd/harmony, pull requests merged in 2024-06, with the labels that each got.

#18 fix(web): do not fail parsing country codes with surrounding spaces
  server/state.ts
Labels: bug, web

#20 feat(Bandcamp): set creative commons license URL if available
  harmonizer/types.ts
  musicbrainz/seeding.ts
  providers/Bandcamp/json_types.ts
  providers/Bandcamp/mod.ts
Labels: feature, Bandcamp

#43 Reword release action "Open in MusicBrainz"
  server/routes/release/actions.tsx
Labels: question, web
